matrix:
  include:
    - os: osx
      osx_image: xcode8.1
      language: objective-c
    - os: osx
      osx_image: xcode9
      language: objective-c
    - os: linux
      language: generic
      sudo: required
      dist: trusty
      env:
        - SWIFT_VERSION="3.0.2"
    - os: linux
      language: generic
      sudo: required
      dist: trusty
      env:
        - SWIFT_VERSION="3.1"
    - os: linux
      language: generic
      sudo: required
      dist: trusty
      env:
        - SWIFT_VERSION="3.1.1"
    - os: linux
      language: generic
      sudo: required
      dist: trusty
      env:
        - SWIFT_VERSION="4.0-DEVELOPMENT-SNAPSHOT-2017-07-24-a"
env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
    - FRAMEWORK_NAME="Threadly"
    - SWIFTENV_ROOT="$HOME/.swiftenv"
    - PATH="$SWIFTENV_ROOT/bin:$SWIFTENV_ROOT/shims:$PATH"
install: ./ci/install.sh
script: ./ci/travis.sh
